### ISSUE TITLE
Configuration file not found

### ISSUE THREAD

**Issue by MkBeeCtrl** [PrestaShop/StarterTheme#146]
I am new to presta so sorry for this question, but I am receving the following error when trying to launch starter theme from prestashop admin.

<img width="1264" alt="screen shot 2016-11-16 at 15 19 31" src="https://cloud.githubusercontent.com/assets/10107362/20350741/551f6112-ac10-11e6-9e9c-145290441d21.png">

I did create theme.yml file and uploaded it to the server, is this the file the error is talking about or it's someting else? I am not sure as it's not covered in the docs. Can't find any reference about this subject anywhere so any tips will be much appreciated

I can see that presta reads the name from my file, here's the rest of the config file, unchanged in comparison to the git version, should I add or changing something here?

```
meta:
  compatibility:
      from: 1.7.0.0
      to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-side-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-side-column:
      name: Two Columns, small right column
      description: Two columns with a small right column

global_settings:
  configuration:
    PS_QUICK_VIEW: false

  hooks:
    custom_hooks:
      - name: displayFooterBefore
        title: displayFooterBefore
        description: Add a widget area above the footer
    modules_to_hook:
      displayNav:
        - ps_shoppingcart
        - ps_languageselector
        - ps_currencyselector
        - ps_customersignin
      displayTop:
        - ps_mainmenu
      displayHome:
        - ps_imageslider
        - ps_featuredproducts
        - ps_banner
      displayFooter:
        - ps_contactinfo

  image_types:
    cart_default:
      width: 80
      height: 80
      scope: [products]
    small_default:
      width: 125
      height: 125
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 300
      height: 300
      scope: [products, categories, manufacturers, suppliers]
    large_default:
      width: 500
      height: 500
      scope: [products]
    home_default:
      width: 250
      height: 250
      scope: [products]
    category_default:
      width: 960
      height: 350
      scope: [categories]

theme_settings:
  default_layout: layout-full-width

  layouts:
    category: layout-left-side-column
    best-sales: layout-left-side-column
```
