### ISSUE TITLE
Assets in theme.yml is not working

### ISSUE THREAD

**Issue by andreacasali** [PrestaShop/StarterTheme#181]
Hi,

reading the doc (http://developers.prestashop.com/themes/assets/index.html) I found that i can add js/css file for specific templates editing the theme.yml file, simply adding (just for example):

```
assets:
  css:
    all:
      - id: bootstrap-style
        path: assets/css/bootstrap.min.css
  js:
    product:
      - id: jquery
        path: assets/js/jquery.min.js
        priority: 200
        position: bottom
```

but it doesn't work. What am I doing wrong?

**Comment by kpodemski** [comment]
@andreacasali it is working but you need to delete config/themes/themename/shop1.json file to reload updated .yml file in your back-office, it is fixed in 1.7.1 but not working as expected on 1.7.0.x

**Comment by andreacasali** [comment]
@kpodemski it works! Thank you very much ;)

**Comment by Louis7777** [comment]
@kpodemski @andreacasali 

I am using 1.7.1.1 and assets are not loaded for child themes, not even the custom.css that is supposed to be loaded by default!

Instead, I get the parent's custom.css. If I register it in theme.yml I still don't get the child custom.css, on the contrary, I get the parent file twice!

```
parent: classic
name: mychildtheme
display_name: A Child Theme
version: 1.0.0
author:
  name: "Myself"
assets:
  # If you're using this theme as child and you want to load
  # the parent theme assets, uncomment this line.
  use_parent_assets: true
  # The following lines are showing how to load assets in your page
  # Uncomment and change value to start loading css or js files
  css:
    all:
      - id: custom-lib-style
        path: assets/css/custom.css
```
